[tox]
requires =
    tox-uv>=1.11.0
isolated_build = true
envlist =
    py39
    py310
    py311
    py312
    py313
    py314

[testenv]
extras = all
deps =
    pytest
    pytest-cov
    hypothesis
    pytest-benchmark
allowlist_externals =
    python
commands =
    python -c "import test.tox_banner"
    ; Can't use importlib or I can't have tests import anything from the test folder!
    ; --import-mode importlib
    python -m pytest test --cov-report term-missing --cov=markpickle
